language: c
os: linux
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
  global:
    - PACKAGE=mock
    - DISTRO=alpine
  jobs:
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.07
    - OCAML_VERSION=4.08
    - OCAML_VERSION=4.09
    - OCAML_VERSION=4.04 PACKAGE=mock-ounit PINS=mock:https://github.com/cryptosense/ocaml-mock.git
    - OCAML_VERSION=4.09 PACKAGE=mock-ounit PINS=mock:https://github.com/cryptosense/ocaml-mock.git
